const UI_STRINGS = {
  pt: {
    loading:            "Traduzindo...",
    back:               "voltar",
    saveWord:           "Salvar palavra",
    wordSaved:          "Palavra salva",
    saved:              "Salvo!",
    otherTranslations:  "Outras traduções",
    examples:           "Exemplos de uso",
    showTranslation:    "ver tradução",
    hideTranslation:    "ocultar",
    listenIn:           "Ouvir em",
    panelSubtitle:      "Painel de controle",
    darkMode:           "Modo escuro",
    shortcutTitle:      "Atalho para falar seleção",
    save:               "Salvar",
    langsTitle:         "Idiomas",
    langFrom:           "De",
    langTo:             "Para",
    uiLangTitle:        "Idioma da interface",
    savedWordsTitle:    "Palavras salvas",
    clearAll:           "Limpar tudo",
    noWords:            "Nenhuma palavra salva ainda.",
    invalidKey:         "Tecla inválida. Use uma letra ou número.",
    shortcutSaved:      "Salvo! Use Ctrl + ",
  },
  en: {
    loading:            "Translating...",
    back:               "back",
    saveWord:           "Save word",
    wordSaved:          "Word saved",
    saved:              "Saved!",
    otherTranslations:  "Other translations",
    examples:           "Usage examples",
    showTranslation:    "show translation",
    hideTranslation:    "hide",
    listenIn:           "Listen in",
    panelSubtitle:      "Control panel",
    darkMode:           "Dark mode",
    shortcutTitle:      "Shortcut to speak selection",
    save:               "Save",
    langsTitle:         "Languages",
    langFrom:           "From",
    langTo:             "To",
    uiLangTitle:        "Interface language",
    savedWordsTitle:    "Saved words",
    clearAll:           "Clear all",
    noWords:            "No saved words yet.",
    invalidKey:         "Invalid key. Use a letter or number.",
    shortcutSaved:      "Saved! Use Ctrl + ",
  },
  es: {
    loading:            "Traduciendo...",
    back:               "volver",
    saveWord:           "Guardar palabra",
    wordSaved:          "Palabra guardada",
    saved:              "¡Guardado!",
    otherTranslations:  "Otras traducciones",
    examples:           "Ejemplos de uso",
    showTranslation:    "ver traducción",
    hideTranslation:    "ocultar",
    listenIn:           "Escuchar en",
    panelSubtitle:      "Panel de control",
    darkMode:           "Modo oscuro",
    shortcutTitle:      "Atajo para hablar selección",
    save:               "Guardar",
    langsTitle:         "Idiomas",
    langFrom:           "De",
    langTo:             "Para",
    uiLangTitle:        "Idioma de la interfaz",
    savedWordsTitle:    "Palabras guardadas",
    clearAll:           "Borrar todo",
    noWords:            "Ninguna palabra guardada aún.",
    invalidKey:         "Tecla inválida. Usa una letra o número.",
    shortcutSaved:      "¡Guardado! Usa Ctrl + ",
  },
  fr: {
    loading:            "Traduction...",
    back:               "retour",
    saveWord:           "Sauvegarder",
    wordSaved:          "Mot sauvegardé",
    saved:              "Sauvegardé !",
    otherTranslations:  "Autres traductions",
    examples:           "Exemples d'utilisation",
    showTranslation:    "voir traduction",
    hideTranslation:    "masquer",
    listenIn:           "Écouter en",
    panelSubtitle:      "Panneau de contrôle",
    darkMode:           "Mode sombre",
    shortcutTitle:      "Raccourci pour lire la sélection",
    save:               "Sauvegarder",
    langsTitle:         "Langues",
    langFrom:           "De",
    langTo:             "Vers",
    uiLangTitle:        "Langue de l'interface",
    savedWordsTitle:    "Mots sauvegardés",
    clearAll:           "Tout effacer",
    noWords:            "Aucun mot sauvegardé.",
    invalidKey:         "Touche invalide. Utilisez une lettre ou un chiffre.",
    shortcutSaved:      "Sauvegardé ! Utilisez Ctrl + ",
  },
  de: {
    loading:            "Übersetzen...",
    back:               "zurück",
    saveWord:           "Wort speichern",
    wordSaved:          "Wort gespeichert",
    saved:              "Gespeichert!",
    otherTranslations:  "Andere Übersetzungen",
    examples:           "Verwendungsbeispiele",
    showTranslation:    "Übersetzung anzeigen",
    hideTranslation:    "ausblenden",
    listenIn:           "Anhören auf",
    panelSubtitle:      "Systemsteuerung",
    darkMode:           "Dunkelmodus",
    shortcutTitle:      "Tastenkürzel zum Vorlesen",
    save:               "Speichern",
    langsTitle:         "Sprachen",
    langFrom:           "Von",
    langTo:             "Nach",
    uiLangTitle:        "Sprache der Benutzeroberfläche",
    savedWordsTitle:    "Gespeicherte Wörter",
    clearAll:           "Alle löschen",
    noWords:            "Noch keine gespeicherten Wörter.",
    invalidKey:         "Ungültige Taste. Verwenden Sie einen Buchstaben oder eine Zahl.",
    shortcutSaved:      "Gespeichert! Verwenden Sie Ctrl + ",
  },
};
