const DONATION = {
  url:    "",
  pixKey: "e3de5893-e0a1-452e-b2ac-348c7ea8180d",  
};

const LANG_TTS = {
  en: "en-US", pt: "pt-BR", es: "es-ES", fr: "fr-FR",
  de: "de-DE", it: "it-IT", ja: "ja-JP", zh: "zh-CN",
  ko: "ko-KR", ru: "ru-RU"
};

const LANG_NAMES = {
  en: "English",   pt: "Português", es: "Español",
  fr: "Français",  de: "Deutsch",   it: "Italiano",
  ja: "日本語",    zh: "中文",      ko: "한국어",   ru: "Русский"
};

const UI_STRINGS = {
  pt: {
    loading:            "Traduzindo...",
    back:               "voltar",
    saveWord:           "Salvar palavra",
    wordSaved:          "Palavra salva",
    saved:              "Salvo!",
    otherTranslations:  "Outras traduções",
    examples:           "Exemplos de uso",
    showTranslation:    "ver tradução",
    hideTranslation:    "ocultar",
    listenIn:           "Ouvir em",
    listenSlow:         "Ouvir devagar",
    panelSubtitle:      "Painel de controle",
    darkMode:           "Modo escuro",
    shortcutTitle:      "Atalho para falar seleção",
    save:               "Salvar",
    langsTitle:         "Idiomas",
    langFrom:           "De",
    langTo:             "Para",
    uiLangTitle:        "Idioma da interface",
    savedWordsTitle:    "Palavras salvas",
    clearAll:           "Limpar tudo",
    noWords:            "Nenhuma palavra salva ainda.",
    invalidKey:         "Tecla inválida. Use uma letra ou número.",
    shortcutSaved:      "Salvo! Use Ctrl + ",
    listenPhrase:       "Ouvir frase",
    deleteWord:         "Remover",
    confirmClearAll:    "Apagar todas as palavras salvas? Esta ação não pode ser desfeita.",
    searchPlaceholder:  "Buscar palavra...",
    export:             "Exportar",
    import:             "Importar",
    importSuccess:      "{n} palavras importadas.",
    importNone:         "Nenhuma palavra nova encontrada.",
    importError:        "Arquivo inválido.",
    wordRemoved:        "removida.",
    undo:               "Desfazer",
    pin:                "Fixar",
    close:              "Fechar",
    errUnavailable:     "Erro: extensão indisponível nesta página.",
    errTranslation:     "Erro: não foi possível traduzir.",
    errUnexpected:      "Erro: resposta inesperada.",
    retry:              "Tentar novamente",
    practice:           "Praticar",
    dueForReview:       "para revisar",
    reveal:             "Revelar",
    knew:               "Sabia ✓",
    didntKnow:          "Não sabia ✗",
    practiceComplete:   "Sessão concluída!",
    openVocab:          "Abrir",
    vocabTitle:         "Vocabulário",
    statWords:          "palavras",
    statMastered:       "dominadas",
    tabList:            "Lista",
    tabPractice:        "Praticar",
    noWordsHint:        "Selecione palavras nas páginas e clique ★ para salvar.",
    practiceHint:       "Escolha um modo de estudo:",
    reviewDue:          "Revisar agendadas",
    reviewDueSub:       "Palavras com revisão pendente",
    reviewAll:          "Revisar tudo",
    reviewAllSub:       "Todas as {n} palavras salvas",
    contextMenuTitle:   "Traduzir com TradupPop",
    removed:            "Removida!",
    practiceMinWords:   "Salve pelo menos 3 palavras para praticar. Você tem {n}.",
    definitions:        "Definição",
    popupLabel:         "Tradução",
    allReviewedToday:   "Tudo revisado por hoje 🎉",
    sortAlpha:          "A–Z",
    sortRecent:         "Mais recentes",
    sortLevel:          "Por nível",
    sortDueFirst:       "A revisar primeiro",
    dirForward:         "Palavra → Tradução",
    dirReverse:         "Tradução → Palavra",
    dirMixed:           "Misto",
    directionLabel:     "Direção dos cards",
    popupModeTitle:     "Onde mostrar a tradução",
    popupModePage:      "Na página",
    popupModeIcon:      "No ícone da extensão",
    iconModeHint:       "Selecione texto e a tradução abre aqui; se não abrir, o ícone mostra um aviso.",
    configureShortcut:  "Configurar atalho do navegador",
    settings:           "Configurações",
    supportTitle:       "Apoie o projeto",
    supportHint:        "Curtiu a extensão? Me pague um café ☕",
    donateBtn:          "Fazer uma doação",
    copyPix:            "Copiar chave Pix",
    pixCopied:          "Chave copiada — valeu! 😊",
    supportBtn:         "Apoiar",
    supportProject:     "Apoiar projeto",
    pixKeyLabel:        "Chave Pix",
    supportThanks:      "Obrigado por usar o TradupPop! 💛",
    langOptions:        { en:"Inglês", pt:"Português", es:"Espanhol", fr:"Francês", de:"Alemão", it:"Italiano", ja:"Japonês", zh:"Chinês", ko:"Coreano", ru:"Russo" },
  },
  en: {
    loading:            "Translating...",
    back:               "back",
    saveWord:           "Save word",
    wordSaved:          "Word saved",
    saved:              "Saved!",
    otherTranslations:  "Other translations",
    examples:           "Usage examples",
    showTranslation:    "show translation",
    hideTranslation:    "hide",
    listenIn:           "Listen in",
    listenSlow:         "Listen slowly",
    panelSubtitle:      "Control panel",
    darkMode:           "Dark mode",
    shortcutTitle:      "Shortcut to speak selection",
    save:               "Save",
    langsTitle:         "Languages",
    langFrom:           "From",
    langTo:             "To",
    uiLangTitle:        "Interface language",
    savedWordsTitle:    "Saved words",
    clearAll:           "Clear all",
    noWords:            "No saved words yet.",
    invalidKey:         "Invalid key. Use a letter or number.",
    shortcutSaved:      "Saved! Use Ctrl + ",
    listenPhrase:       "Listen to phrase",
    deleteWord:         "Remove",
    confirmClearAll:    "Delete all saved words? This cannot be undone.",
    searchPlaceholder:  "Search word...",
    export:             "Export",
    import:             "Import",
    importSuccess:      "{n} words imported.",
    importNone:         "No new words found.",
    importError:        "Invalid file.",
    wordRemoved:        "removed.",
    undo:               "Undo",
    pin:                "Pin",
    close:              "Close",
    errUnavailable:     "Error: extension unavailable on this page.",
    errTranslation:     "Error: could not translate.",
    errUnexpected:      "Error: unexpected response.",
    retry:              "Try again",
    practice:           "Practice",
    dueForReview:       "due for review",
    reveal:             "Reveal",
    knew:               "I knew it ✓",
    didntKnow:          "I didn't know ✗",
    practiceComplete:   "Session complete!",
    openVocab:          "Open",
    vocabTitle:         "Vocabulary",
    statWords:          "words",
    statMastered:       "mastered",
    tabList:            "List",
    tabPractice:        "Practice",
    noWordsHint:        "Select words on pages and click ★ to save.",
    practiceHint:       "Choose a study mode:",
    reviewDue:          "Review scheduled",
    reviewDueSub:       "Words with pending review",
    reviewAll:          "Review all",
    reviewAllSub:       "All {n} saved words",
    contextMenuTitle:   "Translate with TradupPop",
    removed:            "Removed!",
    practiceMinWords:   "Save at least 3 words to practice. You have {n}.",
    definitions:        "Definition",
    popupLabel:         "Translation",
    allReviewedToday:   "All reviewed for today 🎉",
    sortAlpha:          "A–Z",
    sortRecent:         "Most recent",
    sortLevel:          "By level",
    sortDueFirst:       "Due first",
    dirForward:         "Word → Translation",
    dirReverse:         "Translation → Word",
    dirMixed:           "Mixed",
    directionLabel:     "Card direction",
    popupModeTitle:     "Where to show the translation",
    popupModePage:      "On the page",
    popupModeIcon:      "On the extension icon",
    iconModeHint:       "Select text and the translation opens here; if it doesn't, the icon shows a badge.",
    configureShortcut:  "Set browser shortcut",
    settings:           "Settings",
    supportTitle:       "Support the project",
    supportHint:        "Enjoying the extension? Buy me a coffee ☕",
    donateBtn:          "Make a donation",
    copyPix:            "Copy Pix key",
    pixCopied:          "Key copied — thanks! 😊",
    supportBtn:         "Support",
    supportProject:     "Support project",
    pixKeyLabel:        "Pix key",
    supportThanks:      "Thanks for using TradupPop! 💛",
    langOptions:        { en:"English", pt:"Portuguese", es:"Spanish", fr:"French", de:"German", it:"Italian", ja:"Japanese", zh:"Chinese", ko:"Korean", ru:"Russian" },
  },
  es: {
    loading:            "Traduciendo...",
    back:               "volver",
    saveWord:           "Guardar palabra",
    wordSaved:          "Palabra guardada",
    saved:              "¡Guardado!",
    otherTranslations:  "Otras traducciones",
    examples:           "Ejemplos de uso",
    showTranslation:    "ver traducción",
    hideTranslation:    "ocultar",
    listenIn:           "Escuchar en",
    listenSlow:         "Escuchar lento",
    panelSubtitle:      "Panel de control",
    darkMode:           "Modo oscuro",
    shortcutTitle:      "Atajo para hablar selección",
    save:               "Guardar",
    langsTitle:         "Idiomas",
    langFrom:           "De",
    langTo:             "Para",
    uiLangTitle:        "Idioma de la interfaz",
    savedWordsTitle:    "Palabras guardadas",
    clearAll:           "Borrar todo",
    noWords:            "Ninguna palabra guardada aún.",
    invalidKey:         "Tecla inválida. Usa una letra o número.",
    shortcutSaved:      "¡Guardado! Usa Ctrl + ",
    listenPhrase:       "Escuchar frase",
    deleteWord:         "Eliminar",
    confirmClearAll:    "¿Borrar todas las palabras guardadas? Esta acción no se puede deshacer.",
    searchPlaceholder:  "Buscar palabra...",
    export:             "Exportar",
    import:             "Importar",
    importSuccess:      "{n} palabras importadas.",
    importNone:         "No se encontraron palabras nuevas.",
    importError:        "Archivo inválido.",
    wordRemoved:        "eliminada.",
    undo:               "Deshacer",
    pin:                "Fijar",
    close:              "Cerrar",
    errUnavailable:     "Error: extensión no disponible en esta página.",
    errTranslation:     "Error: no se pudo traducir.",
    errUnexpected:      "Error: respuesta inesperada.",
    retry:              "Reintentar",
    practice:           "Practicar",
    dueForReview:       "para revisar",
    reveal:             "Revelar",
    knew:               "Lo sabía ✓",
    didntKnow:          "No lo sabía ✗",
    practiceComplete:   "¡Sesión completada!",
    openVocab:          "Abrir",
    vocabTitle:         "Vocabulario",
    statWords:          "palabras",
    statMastered:       "dominadas",
    tabList:            "Lista",
    tabPractice:        "Practicar",
    noWordsHint:        "Selecciona palabras en las páginas y haz clic en ★ para guardar.",
    practiceHint:       "Elige un modo de estudio:",
    reviewDue:          "Revisar programadas",
    reviewDueSub:       "Palabras con revisión pendiente",
    reviewAll:          "Revisar todo",
    reviewAllSub:       "Todas las {n} palabras guardadas",
    contextMenuTitle:   "Traducir con TradupPop",
    removed:            "¡Eliminada!",
    practiceMinWords:   "Guarda al menos 3 palabras para practicar. Tienes {n}.",
    definitions:        "Definición",
    popupLabel:         "Traducción",
    allReviewedToday:   "Todo revisado por hoy 🎉",
    sortAlpha:          "A–Z",
    sortRecent:         "Más recientes",
    sortLevel:          "Por nivel",
    sortDueFirst:       "Pendientes primero",
    dirForward:         "Palabra → Traducción",
    dirReverse:         "Traducción → Palabra",
    dirMixed:           "Mixto",
    directionLabel:     "Dirección de las tarjetas",
    popupModeTitle:     "Dónde mostrar la traducción",
    popupModePage:      "En la página",
    popupModeIcon:      "En el icono de la extensión",
    iconModeHint:       "Selecciona texto y la traducción se abre aquí; si no se abre, el icono muestra un aviso.",
    configureShortcut:  "Configurar atajo del navegador",
    settings:           "Configuración",
    supportTitle:       "Apoya el proyecto",
    supportHint:        "¿Te gusta la extensión? Invítame a un café ☕",
    donateBtn:          "Hacer una donación",
    copyPix:            "Copiar clave Pix",
    pixCopied:          "Clave copiada — ¡gracias! 😊",
    supportBtn:         "Apoyar",
    supportProject:     "Apoyar proyecto",
    pixKeyLabel:        "Clave Pix",
    supportThanks:      "¡Gracias por usar TradupPop! 💛",
    langOptions:        { en:"Inglés", pt:"Portugués", es:"Español", fr:"Francés", de:"Alemán", it:"Italiano", ja:"Japonés", zh:"Chino", ko:"Coreano", ru:"Ruso" },
  },
  fr: {
    loading:            "Traduction...",
    back:               "retour",
    saveWord:           "Sauvegarder",
    wordSaved:          "Mot sauvegardé",
    saved:              "Sauvegardé !",
    otherTranslations:  "Autres traductions",
    examples:           "Exemples d'utilisation",
    showTranslation:    "voir traduction",
    hideTranslation:    "masquer",
    listenIn:           "Écouter en",
    listenSlow:         "Écouter lentement",
    panelSubtitle:      "Panneau de contrôle",
    darkMode:           "Mode sombre",
    shortcutTitle:      "Raccourci pour lire la sélection",
    save:               "Sauvegarder",
    langsTitle:         "Langues",
    langFrom:           "De",
    langTo:             "Vers",
    uiLangTitle:        "Langue de l'interface",
    savedWordsTitle:    "Mots sauvegardés",
    clearAll:           "Tout effacer",
    noWords:            "Aucun mot sauvegardé.",
    invalidKey:         "Touche invalide. Utilisez une lettre ou un chiffre.",
    shortcutSaved:      "Sauvegardé ! Utilisez Ctrl + ",
    listenPhrase:       "Écouter la phrase",
    deleteWord:         "Supprimer",
    confirmClearAll:    "Supprimer tous les mots sauvegardés ? Cette action est irréversible.",
    searchPlaceholder:  "Chercher un mot...",
    export:             "Exporter",
    import:             "Importer",
    importSuccess:      "{n} mots importés.",
    importNone:         "Aucun nouveau mot trouvé.",
    importError:        "Fichier invalide.",
    wordRemoved:        "supprimé.",
    undo:               "Annuler",
    pin:                "Épingler",
    close:              "Fermer",
    errUnavailable:     "Erreur : extension indisponible sur cette page.",
    errTranslation:     "Erreur : traduction impossible.",
    errUnexpected:      "Erreur : réponse inattendue.",
    retry:              "Réessayer",
    practice:           "Pratiquer",
    dueForReview:       "à réviser",
    reveal:             "Révéler",
    knew:               "Je savais ✓",
    didntKnow:          "Je ne savais pas ✗",
    practiceComplete:   "Séance terminée !",
    openVocab:          "Ouvrir",
    vocabTitle:         "Vocabulaire",
    statWords:          "mots",
    statMastered:       "maîtrisés",
    tabList:            "Liste",
    tabPractice:        "Pratiquer",
    noWordsHint:        "Sélectionnez des mots sur les pages et cliquez ★ pour sauvegarder.",
    practiceHint:       "Choisissez un mode d'étude :",
    reviewDue:          "Réviser les planifiés",
    reviewDueSub:       "Mots avec révision en attente",
    reviewAll:          "Tout réviser",
    reviewAllSub:       "Tous les {n} mots sauvegardés",
    contextMenuTitle:   "Traduire avec TradupPop",
    removed:            "Supprimé !",
    practiceMinWords:   "Sauvegardez au moins 3 mots pour pratiquer. Vous en avez {n}.",
    definitions:        "Définition",
    popupLabel:         "Traduction",
    allReviewedToday:   "Tout révisé pour aujourd'hui 🎉",
    sortAlpha:          "A–Z",
    sortRecent:         "Plus récents",
    sortLevel:          "Par niveau",
    sortDueFirst:       "À réviser d'abord",
    dirForward:         "Mot → Traduction",
    dirReverse:         "Traduction → Mot",
    dirMixed:           "Mixte",
    directionLabel:     "Direction des cartes",
    popupModeTitle:     "Où afficher la traduction",
    popupModePage:      "Sur la page",
    popupModeIcon:      "Sur l'icône de l'extension",
    iconModeHint:       "Sélectionnez du texte et la traduction s'ouvre ici ; sinon, l'icône affiche un badge.",
    configureShortcut:  "Configurer le raccourci",
    settings:           "Paramètres",
    supportTitle:       "Soutenez le projet",
    supportHint:        "Vous aimez l'extension ? Offrez-moi un café ☕",
    donateBtn:          "Faire un don",
    copyPix:            "Copier la clé Pix",
    pixCopied:          "Clé copiée — merci ! 😊",
    supportBtn:         "Soutenir",
    supportProject:     "Soutenir le projet",
    pixKeyLabel:        "Clé Pix",
    supportThanks:      "Merci d'utiliser TradupPop ! 💛",
    langOptions:        { en:"Anglais", pt:"Portugais", es:"Espagnol", fr:"Français", de:"Allemand", it:"Italien", ja:"Japonais", zh:"Chinois", ko:"Coréen", ru:"Russe" },
  },
  de: {
    loading:            "Übersetzen...",
    back:               "zurück",
    saveWord:           "Wort speichern",
    wordSaved:          "Wort gespeichert",
    saved:              "Gespeichert!",
    otherTranslations:  "Andere Übersetzungen",
    examples:           "Verwendungsbeispiele",
    showTranslation:    "Übersetzung anzeigen",
    hideTranslation:    "ausblenden",
    listenIn:           "Anhören auf",
    listenSlow:         "Langsam anhören",
    panelSubtitle:      "Systemsteuerung",
    darkMode:           "Dunkelmodus",
    shortcutTitle:      "Tastenkürzel zum Vorlesen",
    save:               "Speichern",
    langsTitle:         "Sprachen",
    langFrom:           "Von",
    langTo:             "Nach",
    uiLangTitle:        "Sprache der Benutzeroberfläche",
    savedWordsTitle:    "Gespeicherte Wörter",
    clearAll:           "Alle löschen",
    noWords:            "Noch keine gespeicherten Wörter.",
    invalidKey:         "Ungültige Taste. Verwenden Sie einen Buchstaben oder eine Zahl.",
    shortcutSaved:      "Gespeichert! Verwenden Sie Ctrl + ",
    listenPhrase:       "Satz anhören",
    deleteWord:         "Entfernen",
    confirmClearAll:    "Alle gespeicherten Wörter löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
    searchPlaceholder:  "Wort suchen...",
    export:             "Exportieren",
    import:             "Importieren",
    importSuccess:      "{n} Wörter importiert.",
    importNone:         "Keine neuen Wörter gefunden.",
    importError:        "Ungültige Datei.",
    wordRemoved:        "entfernt.",
    undo:               "Rückgängig",
    pin:                "Anheften",
    close:              "Schließen",
    errUnavailable:     "Fehler: Erweiterung auf dieser Seite nicht verfügbar.",
    errTranslation:     "Fehler: Übersetzung fehlgeschlagen.",
    errUnexpected:      "Fehler: Unerwartete Antwort.",
    retry:              "Erneut versuchen",
    practice:           "Üben",
    dueForReview:       "zur Überprüfung",
    reveal:             "Aufdecken",
    knew:               "Gewusst ✓",
    didntKnow:          "Nicht gewusst ✗",
    practiceComplete:   "Einheit abgeschlossen!",
    openVocab:          "Öffnen",
    vocabTitle:         "Vokabular",
    statWords:          "Wörter",
    statMastered:       "gemeistert",
    tabList:            "Liste",
    tabPractice:        "Üben",
    noWordsHint:        "Wählen Sie Wörter auf Seiten aus und klicken Sie ★ zum Speichern.",
    practiceHint:       "Wählen Sie einen Lernmodus:",
    reviewDue:          "Geplante überprüfen",
    reviewDueSub:       "Wörter mit ausstehender Überprüfung",
    reviewAll:          "Alles überprüfen",
    reviewAllSub:       "Alle {n} gespeicherten Wörter",
    contextMenuTitle:   "Mit TradupPop übersetzen",
    removed:            "Entfernt!",
    practiceMinWords:   "Speichern Sie mindestens 3 Wörter zum Üben. Sie haben {n}.",
    definitions:        "Definition",
    popupLabel:         "Übersetzung",
    allReviewedToday:   "Alles für heute überprüft 🎉",
    sortAlpha:          "A–Z",
    sortRecent:         "Neueste zuerst",
    sortLevel:          "Nach Stufe",
    sortDueFirst:       "Fällige zuerst",
    dirForward:         "Wort → Übersetzung",
    dirReverse:         "Übersetzung → Wort",
    dirMixed:           "Gemischt",
    directionLabel:     "Kartenrichtung",
    popupModeTitle:     "Wo die Übersetzung erscheint",
    popupModePage:      "Auf der Seite",
    popupModeIcon:      "Am Erweiterungssymbol",
    iconModeHint:       "Text auswählen und die Übersetzung öffnet sich hier; andernfalls zeigt das Symbol einen Hinweis.",
    configureShortcut:  "Tastenkürzel festlegen",
    settings:           "Einstellungen",
    supportTitle:       "Projekt unterstützen",
    supportHint:        "Gefällt dir die Erweiterung? Spendier mir einen Kaffee ☕",
    donateBtn:          "Spenden",
    copyPix:            "Pix-Schlüssel kopieren",
    pixCopied:          "Schlüssel kopiert — danke! 😊",
    supportBtn:         "Unterstützen",
    supportProject:     "Projekt unterstützen",
    pixKeyLabel:        "Pix-Schlüssel",
    supportThanks:      "Danke, dass du TradupPop nutzt! 💛",
    langOptions:        { en:"Englisch", pt:"Portugiesisch", es:"Spanisch", fr:"Französisch", de:"Deutsch", it:"Italienisch", ja:"Japanisch", zh:"Chinesisch", ko:"Koreanisch", ru:"Russisch" },
  },
};

// Dark mode: valor salvo tem prioridade; sem valor salvo, segue o sistema.
// Carregado também no service worker (sem window), por isso o guard.
function resolveDarkMode(storedValue) {
  if (storedValue === undefined || storedValue === null) {
    if (typeof window === "undefined" || !window.matchMedia) return false;
    return window.matchMedia("(prefers-color-scheme: dark)").matches;
  }
  return !!storedValue;
}
